
import React from 'react';
import { useTaxStore } from '@/store/taxStore';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';

const IncomeForm = () => {
  const { incomeValues, setIncomeValues } = useTaxStore();

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    // Only allow numbers and decimal points
    if (/^(\d*\.?\d*)$/.test(value) || value === '') {
      setIncomeValues({ [name]: value });
    }
  };

  return (
    <Card className="w-full">
      <CardHeader>
        <CardTitle className="text-2xl text-center">Income Information</CardTitle>
        <CardDescription className="text-center">
          Please enter your personal and S-Corp income information
        </CardDescription>
      </CardHeader>
      <CardContent>
        <div className="space-y-6">
          <div className="space-y-2">
            <Label htmlFor="personalIncome">Personal Income ($)</Label>
            <Input
              id="personalIncome"
              name="personalIncome"
              value={incomeValues.personalIncome}
              onChange={handleChange}
              placeholder="0.00"
              className="text-right"
            />
            <p className="text-sm text-muted-foreground">
              Enter your total personal income from all sources excluding your S-Corp
            </p>
          </div>

          <div className="space-y-2">
            <Label htmlFor="sCorpIncome">S-Corporation Income ($)</Label>
            <Input
              id="sCorpIncome"
              name="sCorpIncome"
              value={incomeValues.sCorpIncome}
              onChange={handleChange}
              placeholder="0.00"
              className="text-right"
            />
            <p className="text-sm text-muted-foreground">
              Enter the total revenue generated by your S-Corporation
            </p>
          </div>
        </div>
      </CardContent>
    </Card>
  );
};

export default IncomeForm;
